### ISSUE TITLE
Uninitialized variable

### ISSUE THREAD

**Issue by zsxshawn** [Chinmaykd21/CSCI8000_Project_Compiler#11]
Project: Compiler
Report By: Team Blue
Vulnerability Type: Uninitialized variable
Analysis Method Used: CppCheck
Vulnerability Description:
parseTree.cpp:275:37: error: Uninitialized variable: closeQuotes [uninitvar]
                                j = closeQuotes + 1;

**Comment by ChinmayDeosthali** [comment]
Thanks for pointing out the error. This issue has been solved. Please refer 7683cd9
Closing the issue.
