### ISSUE TITLE
Uninitialized variable

### ISSUE THREAD

**Issue by zsxshawn** [Chinmaykd21/CSCI8000_Project_Compiler#12]
Project: Compiler
Report By:Team Blue
Vulnerability Type: Uninitialized variable
Analysis Method Used: CppCheck
Vulnerability Description:
compiler.cpp:937:37: error: Uninitialized variable: closeQuotes [uninitvar]
                                j = closeQuotes + 1;

**Comment by Chinmaykd21** [comment]
This issue has been resolved. commit id : 61e2ff7ea1ccac7f19c69a6ad3246e6c26f63b09
